# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东东东农场-工具人

on:
  workflow_dispatch:
  schedule:
    - cron: '20 23,4,10 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install request
          npm install --save got
          npm install tough-cookie
      - name: '京东东东农场-工具人'
        env: 
            COOKIE: ${{secrets.JD_COOKIE_GJR}}
            TG_BOT_TOKEN :  ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID :  ${{secrets.TG_USER_ID}}
            REMOTE_URL: https://gitee.com/lxk0301/scripts/raw/master/jd_fruit.js
            CUSTOM_REPLACE: '[{key : /await notify\.sendNotify.+/g,value : ""}]'
            MULT_CUSTOM_REPLACE: '[[{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-WJY2'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`2305d2eca60b4bc9aa95ac6bbd1dcfa4@1f6e81ae66294d14b0d0e27d07236e8c@49388ab5f2654460be8a4a44cfde6a92@8896a3d57f774c8ba8a3432012c90efe`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-YTX2'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`b4f36c1c632746a8bcc3899a11cc19f6@11705719f6e34c6a95913acc5d23d640@8896a3d57f774c8ba8a3432012c90efe@657789f6f682430fa8e40d44d7918fdc`]"}]
                                  ]'
        run: |
          node 'scripts/remote/runRemoteScripts.js'
