# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东东东农场

on:
  workflow_dispatch:
  schedule:
    - cron: '20 23,4,10 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install request
          npm install --save got
          npm install tough-cookie
      - name: '京东东东农场'
        env: 
            COOKIE: ${{secrets.JD_COOKIE}}
            TG_BOT_TOKEN :  ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID :  ${{secrets.TG_USER_ID}}
            REMOTE_URL: https://raw.githubusercontent.com/lxk0301/scripts/master/jd_fruit.js
            CUSTOM_REPLACE: '[{key : /await notify\.sendNotify.+/g,value : ""}]'
            MULT_CUSTOM_REPLACE: '[[{key : /const \$.+/,value : "const $ = new Env(''东东农场-YTX'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`e3ff185ff53643308ab2b1a6afb3533e@323dbdbbfc824faa81b8927cd95bf975@732c806d465d427aab0c948e2ef8de17@5fe4179a7903433b898e6849409ad885`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-SR'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`967a8e63fa2148208c1385ed34641ede@b8359db44d244b1f8c36e399926eb5d5@6d7041df49b14747b7ea240efcbe3b59@7b6a724115984e968ec962bf333c0d3b`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-LJ'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`1d5c06e54d7445fd974322a30e5e0760@2305d2eca60b4bc9aa95ac6bbd1dcfa4@4c751756e1ba497e9c98eccb1369b73a@ba1ba118597c4caa9d079842963cdc7f`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-ZGX'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`49388ab5f2654460be8a4a44cfde6a92@1d5c06e54d7445fd974322a30e5e0760@4c751756e1ba497e9c98eccb1369b73a@ba1ba118597c4caa9d079842963cdc7f`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-WJY'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`2305d2eca60b4bc9aa95ac6bbd1dcfa4@9b4cb4da34e84b00a7cd804d9db5be38@1d5c06e54d7445fd974322a30e5e0760@ba1ba118597c4caa9d079842963cdc7f`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-LJ2'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`1d5c06e54d7445fd974322a30e5e0760@9b4cb4da34e84b00a7cd804d9db5be38@4c751756e1ba497e9c98eccb1369b73a@1f6e81ae66294d14b0d0e27d07236e8c`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-RQ'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`9b4cb4da34e84b00a7cd804d9db5be38@8896a3d57f774c8ba8a3432012c90efe@657789f6f682430fa8e40d44d7918fdc@ba1ba118597c4caa9d079842963cdc7f`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-WRX'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`657789f6f682430fa8e40d44d7918fdc@2305d2eca60b4bc9aa95ac6bbd1dcfa4@8896a3d57f774c8ba8a3432012c90efe@ba1ba118597c4caa9d079842963cdc7f`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-GC'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`2305d2eca60b4bc9aa95ac6bbd1dcfa4@9b4cb4da34e84b00a7cd804d9db5be38@657789f6f682430fa8e40d44d7918fdc@4c751756e1ba497e9c98eccb1369b73a`]"}],
                                   [{key : /const \$.+/,value : "const $ = new Env(''东东农场-WSR'')"},{key : /const jdFruitShareCodes.+/,value : "const jdFruitShareCodes = [`9b4cb4da34e84b00a7cd804d9db5be38@657789f6f682430fa8e40d44d7918fdc@4c751756e1ba497e9c98eccb1369b73a@8896a3d57f774c8ba8a3432012c90efe`]"}]
                                  ]'
        run: |
          node 'scripts/remote/runRemoteScripts.js'
