# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东种豆得豆

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23,0-15/1 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install request
          npm install --save got
          npm install tough-cookie
      - name: '京东种豆得豆'
        env: 
            COOKIE: ${{secrets.JD_COOKIE}}
            TG_BOT_TOKEN :  ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID :  ${{secrets.TG_USER_ID}}
            REMOTE_URL: https://raw.githubusercontent.com/lxk0301/scripts/master/jd_plantBean.js
            CUSTOM_REPLACE: '[{key : /let jdNotify.+/,value : "let jdNotify = true"},
                              {key : /await notify.sendNotify.+/g,value : ""},
                              {key : /newShareCodes = shareCodes.+/,value : "newShareCodes = [`4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a`]"}
                             ]'
            MULT_CUSTOM_REPLACE: '[[{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`uqxphhjuyv4prshagyxrns5i4u5ac3f4ijdgqji@6gqunvc6pqurlxqun5z4kq4cvymvarmageqo5ny@fqiuif3ihmddqlj2gp5fx3m6bq`] "}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a@mlrdw3aw26j3wcz3m4oixobt6pc6wcd3foqccgi@s23bnhsjdbqan5o7uz2qq36q3i5ac3f4ijdgqji`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@ezkhd4q2ixspj62ta3scstfk3u`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@ezkhd4q2ixspj62ta3scstfk3u`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a@mlrdw3aw26j3wcz3m4oixobt6pc6wcd3foqccgi@s23bnhsjdbqan5o7uz2qq36q3i5ac3f4ijdgqji`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@s23bnhsjdbqan5o7uz2qq36q3i5ac3f4ijdgqji`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@s23bnhsjdbqan5o7uz2qq36q3i5ac3f4ijdgqji`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@s23bnhsjdbqan5o7uz2qq36q3i5ac3f4ijdgqji`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@4npkonnsy7xi2k7k2xwei2iqwtb727s3zwxun6a@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a`]"}],
                                   [{key : /const jdPlantBeanShareCodes.+/,value : "const jdPlantBeanShareCodes = [`e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a@pw3fgi6zjxfzsnvwbyglqndose@e7lhibzb3zek34vafvcqnnbpqej3d4y2fheri5a`]"}]
                                  ]'
        run: |
          node 'scripts/remote/runRemoteScripts.js'
