# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京小超做任务

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */4 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
          npm install request
          npm install --save got
          npm install tough-cookie
      - name: '京小超做任务'
        env: 
            COOKIE: ${{secrets.JD_COOKIE}}
            TG_BOT_TOKEN :  ${{secrets.TG_BOT_TOKEN}}
            TG_USER_ID :  ${{secrets.TG_USER_ID}}
            REMOTE_URL: https://raw.githubusercontent.com/lxk0301/scripts/master/jd_superMarket.js
            CUSTOM_REPLACE: '[{key : /const jdNotify =.+/,value : "const jdNotify = true"},
                              {key : /await notify.sendNotify.+/g,value : ""}
                             ]'
            MULT_CUSTOM_REPLACE: '[[{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-YTX'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`IM2b1O1kwWk@eU9Ya-_mYvon92nSzXYT1Q@eU9YaLi7Ya4gpG7XmCUW1Q`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-SR'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`eU9Ya-ywYf4n9DrXnXJA0Q@eU9Ya-_mYvon92nSzXYT1Q@eU9YaLi7Ya4gpG7XmCUW1Q`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-LJ'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`eU9Ya-ywYf4n9DrXnXJA0Q@eU9YaOuxb_si9WzSzXtB3g@eU9YaLi7Ya4gpG7XmCUW1Q`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-ZGX'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`eU9Ya-ywYf4n9DrXnXJA0Q@eU9YaOuxb_si9WzSzXtB3g@eU9YaeS0Z68m9G2DmndC0w`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-WJY'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`eU9YaOuxb_si9WzSzXtB3g@eU9YaeS0Z68m9G2DmndC0w@Ihkzbeq6b_0m8QGI`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-LJ2'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`eU9YaeS0Z68m9G2DmndC0w@Ihkzbeq6b_0m8QGI@JB81aO-0YvknnjM`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-RQ'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`Ihkzbeq6b_0m8QGI@JB81aO-0YvknnjM@eU9Yar2wZ6kv8jyBmiZC1g`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-WRX'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`JB81aO-0YvknnjM@eU9Yar2wZ6kv8jyBmiZC1g@IM2b1O1kwWk`]"}],
                                   [{key : /const \$.+\(''(.+)''\);/,value : "const $ = new Env(''$1-GC'')"},{key : /const jdShareCodes.+/,value : "const jdShareCodes = [`eU9Yar2wZ6kv8jyBmiZC1g@IM2b1O1kwWk@eU9Ya-_mYvon92nSzXYT1Q`]"}]
                                  ]'
        run: |
          node 'scripts/remote/runRemoteScripts.js'
